In [2]:
import numpy as np

In [33]:
a = np.arange(27).reshape(3,3,3)
b = np.arange(28,55).reshape(3,3,3)

In [27]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
a.ndim

3

In [9]:
a.size

27

In [10]:
a.shape

(3, 3, 3)

In [11]:
a.dtype

dtype('int32')

In [12]:
a.itemsize

4

In [13]:
a.data

In [14]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [15]:
#Access the third element of the third array of the first array for "a"

In [16]:
a[0,2,2]

8

In [19]:
#Access the first element of the first array of the third array for "a"

In [20]:
a[2,0,0]

18

In [28]:
b

array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [29]:
a+b

array([[[28, 30, 32],
        [34, 36, 38],
        [40, 42, 44]],

       [[46, 48, 50],
        [52, 54, 56],
        [58, 60, 62]],

       [[64, 66, 68],
        [70, 72, 74],
        [76, 78, 80]]])

In [34]:
b-a

array([[[28, 28, 28],
        [28, 28, 28],
        [28, 28, 28]],

       [[28, 28, 28],
        [28, 28, 28],
        [28, 28, 28]],

       [[28, 28, 28],
        [28, 28, 28],
        [28, 28, 28]]])

In [35]:
a*b

array([[[   0,   29,   60],
        [  93,  128,  165],
        [ 204,  245,  288]],

       [[ 333,  380,  429],
        [ 480,  533,  588],
        [ 645,  704,  765]],

       [[ 828,  893,  960],
        [1029, 1100, 1173],
        [1248, 1325, 1404]]])

In [36]:
a**b

array([[[          0,           1,  1073741824],
        [ 1264544299,           0, -1671385723],
        [          0,   613813847,           0]],

       [[  309963689,           0, -1412675005],
        [          0,   331227181,           0],
        [  -45233233,           0,  1970127057]],

       [[          0, -2041018277,           0],
        [ -871208107,           0, -1672161785],
        [          0,   270245241,           0]]], dtype=int32)

In [39]:
100*np.sin(a)

array([[[  0.        ,  84.14709848,  90.92974268],
        [ 14.11200081, -75.68024953, -95.89242747],
        [-27.94154982,  65.69865987,  98.93582466]],

       [[ 41.21184852, -54.40211109, -99.99902066],
        [-53.6572918 ,  42.01670368,  99.06073557],
        [ 65.02878402, -28.79033167, -96.13974919]],

       [[-75.09872468,  14.98772097,  91.29452507],
        [ 83.66556385,  -0.88513093, -84.62204042],
        [-90.5578362 , -13.23517501,  76.25584505]]])

In [40]:
100*np.cos(a)

array([[[100.        ,  54.03023059, -41.61468365],
        [-98.99924966, -65.36436209,  28.36621855],
        [ 96.01702867,  75.39022543, -14.55000338]],

       [[-91.11302619, -83.90715291,   0.4425698 ],
        [ 84.38539587,  90.74467815,  13.67372182],
        [-75.96879129, -95.76594803, -27.51633381]],

       [[ 66.03167082,  98.87046182,  40.80820618],
        [-54.77292602, -99.99608264, -53.28330203],
        [ 42.41790073,  99.12028119,  64.69193223]]])

In [41]:
a<10

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [42]:
a>10

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [44]:
a[a<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# matrix product
a @ b

array([[[  99,  102,  105],
        [ 378,  390,  402],
        [ 657,  678,  699]],

       [[1206, 1236, 1266],
        [1566, 1605, 1644],
        [1926, 1974, 2022]],

       [[2799, 2856, 2913],
        [3240, 3306, 3372],
        [3681, 3756, 3831]]])

In [48]:
# another matrix product
a.dot(b)

array([[[[  99,  102,  105],
         [ 126,  129,  132],
         [ 153,  156,  159]],

        [[ 378,  390,  402],
         [ 486,  498,  510],
         [ 594,  606,  618]],

        [[ 657,  678,  699],
         [ 846,  867,  888],
         [1035, 1056, 1077]]],


       [[[ 936,  966,  996],
         [1206, 1236, 1266],
         [1476, 1506, 1536]],

        [[1215, 1254, 1293],
         [1566, 1605, 1644],
         [1917, 1956, 1995]],

        [[1494, 1542, 1590],
         [1926, 1974, 2022],
         [2358, 2406, 2454]]],


       [[[1773, 1830, 1887],
         [2286, 2343, 2400],
         [2799, 2856, 2913]],

        [[2052, 2118, 2184],
         [2646, 2712, 2778],
         [3240, 3306, 3372]],

        [[2331, 2406, 2481],
         [3006, 3081, 3156],
         [3681, 3756, 3831]]]])

In [68]:
c = np.ones((2,2))
e = np.zeros((3,3))

In [50]:
c

array([[1., 1.],
       [1., 1.]])

In [51]:
c *= 3

In [52]:
c

array([[3., 3.],
       [3., 3.]])

In [53]:
c -= 2

In [54]:
c

array([[1., 1.],
       [1., 1.]])

In [56]:
a.sum()

351

In [57]:
a.min()

0

In [58]:
a.max()

26

In [59]:
d = np.arange(100)*3

In [67]:
d
d[50:60]

array([150, 153, 156, 159, 162, 165, 168, 171, 174, 177])

In [61]:
d[::2]

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150,
       156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228,
       234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294])

In [64]:
d[-90]

30

In [69]:
d[-10]

270

In [73]:
f = np.arange(12)

In [74]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
fnew = f.reshape(3,4)

In [76]:
fnew

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])